### ISSUE TITLE
Option to select multiple items without hiding dropdown

### ISSUE THREAD

**Issue by t0rum** [srigar/multiselect-react-dropdown#18]
It would be great if there were option to make dropdown stay open on item selection.

It is useful, if user often selects several options in a row.

**Comment by srigar** [comment]
Fix is available in @1.4.3. Use prop called `closeOnSelect` with value `false`. Currently there is a flickering, will resolve it soon

**Comment by 4kets** [comment]
Has the flickering been fixed? cause when i use this option it closes the dropdown but right after closing it opens again

**Comment by 4kets** [comment]
and after removing an item in the dropdown from the selected values it closes and does not open again

**Comment by GeniaT** [comment]
Issue closed but not fixed, not good. The prop actually seems to reopen the dropdown instead of just keeping it opened.

**Comment by Prakash-karena** [comment]
On item removed drop down get closed
